"""
Preview API endpoints
"""
import logging
from fastapi import APIRouter, Depends, HTTPException, status, Request
from fastapi.responses import FileResponse, HTMLResponse
from fastapi.templating import Jinja2Templates
from sqlalchemy.orm import Session
from pathlib import Path
from typing import List
from pydantic import BaseModel

from app.db.base import get_db
from app.db.models import Session as SessionModel, FieldValue, TemplateField
from app.db.models.field_value import FieldValueStatus
from app.services.preview_service import PreviewService

logger = logging.getLogger(__name__)

router = APIRouter()

# Templates directory for HTML
# Path: backend/templates/html/ or /app/templates/html/ in Docker
# In Docker: /app/app/api/v1/preview.py -> need /app/templates/html/
# Locally: backend/app/api/v1/preview.py -> need backend/templates/html/
backend_dir = Path(__file__).parent.parent.parent.parent  # Go up to /app or backend root
templates_dir = backend_dir / "templates" / "html"
templates_dir.mkdir(parents=True, exist_ok=True)
templates = Jinja2Templates(directory=str(templates_dir))


@router.get("/sessions/{session_uuid}/preview", tags=["preview"])
def get_preview(
    session_uuid: str,
    db: Session = Depends(get_db)
):
    """
    Generate and return a DOCX preview for a session.
    
    The preview file is generated by merging all field values into the session's template.
    If the preview already exists, it will be overwritten with updated values.
    
    Args:
        session_uuid: UUID of the session
        db: Database session
        
    Returns:
        FileResponse with the preview DOCX file
        
    Raises:
        404: If session not found
        500: If preview generation fails
    """
    # Get the session by UUID from the database
    session = db.query(SessionModel).filter(SessionModel.uuid == session_uuid).first()
    
    if not session:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Session not found: {session_uuid}"
        )
    
    try:
        # Call PreviewService.generate_preview(session)
        preview_service = PreviewService(db)
        preview_path = preview_service.generate_preview(session)
        
        # Verify the file exists
        preview_file = Path(preview_path)
        if not preview_file.exists():
            logger.error(f"Preview file was not created: {preview_path}")
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail="Preview file generation failed"
            )
        
        # Return the preview file using FileResponse
        # Set correct MIME type for DOCX files
        return FileResponse(
            path=preview_path,
            media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            filename=f"session_{session_uuid}_preview.docx"
        )
        
    except FileNotFoundError as e:
        logger.error(f"Template file not found for session {session_uuid}: {str(e)}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Template file not found: {str(e)}"
        )
    except ValueError as e:
        logger.error(f"Invalid session data for {session_uuid}: {str(e)}")
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(e)
        )
    except Exception as e:
        logger.error(f"Error generating preview for session {session_uuid}: {str(e)}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to generate preview: {str(e)}"
        )


# Pydantic models for API requests/responses
class FieldValueResponse(BaseModel):
    id: int
    field_key: str
    display_name: str
    placeholder: str
    current_value: str
    extracted_value: str | None
    manual_value: str | None
    field_value_id: int
    description: str | None
    
    class Config:
        from_attributes = True


class FieldValueUpdateRequest(BaseModel):
    value: str


@router.get("/sessions/{session_uuid}/fields", response_model=List[FieldValueResponse], tags=["preview"])
def get_session_fields(
    session_uuid: str,
    db: Session = Depends(get_db)
):
    """
    Get all field values for a session with their metadata.
    
    Returns a list of all fields with their current values, extracted values, and manual values.
    """
    session = db.query(SessionModel).filter(SessionModel.uuid == session_uuid).first()
    
    if not session:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Session not found: {session_uuid}"
        )
    
    # Get all field values for this session
    field_values = db.query(FieldValue).filter(
        FieldValue.session_id == session.id
    ).all()
    
    result = []
    for fv in field_values:
        template_field = fv.template_field
        if not template_field:
            continue
            
        result.append(FieldValueResponse(
            id=fv.id,
            field_key=template_field.field_key,
            display_name=template_field.display_name,
            placeholder=template_field.placeholder,
            current_value=fv.final_value or "",
            extracted_value=fv.extracted_value,
            manual_value=fv.manual_value,
            field_value_id=fv.id,
            description=template_field.description
        ))
    
    # Sort by field_order if available, otherwise by display_name
    result.sort(key=lambda x: (getattr(x, 'field_order', 999), x.display_name))
    
    return result


@router.patch("/sessions/{session_uuid}/fields/{field_value_id}", tags=["preview"])
def update_field_value(
    session_uuid: str,
    field_value_id: int,
    update_request: FieldValueUpdateRequest,
    db: Session = Depends(get_db)
):
    """
    Update a field value for a session.
    
    Sets the manual_value, which takes priority over extracted_value.
    """
    # Verify session exists
    session = db.query(SessionModel).filter(SessionModel.uuid == session_uuid).first()
    if not session:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Session not found: {session_uuid}"
        )
    
    # Get the field value
    field_value = db.query(FieldValue).filter(
        FieldValue.id == field_value_id,
        FieldValue.session_id == session.id
    ).first()
    
    if not field_value:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Field value not found: {field_value_id}"
        )
    
    # Update the manual value
    field_value.manual_value = update_request.value if update_request.value.strip() else None
    field_value.status = FieldValueStatus.MANUAL if field_value.manual_value else FieldValueStatus.EXTRACTED
    
    db.commit()
    db.refresh(field_value)
    
    # Regenerate preview silently (don't return file, just update on server)
    preview_updated = False
    try:
        preview_service = PreviewService(db)
        preview_service.generate_preview(session)
        preview_updated = True
    except Exception as e:
        logger.warning(f"Failed to regenerate preview after field update: {str(e)}")
        # Don't fail the request if preview generation fails
    
    return {
        "id": field_value.id,
        "field_key": field_value.template_field.field_key if field_value.template_field else None,
        "current_value": field_value.final_value or "",
        "manual_value": field_value.manual_value,
        "extracted_value": field_value.extracted_value,
        "preview_updated": preview_updated
    }


@router.post("/sessions/{session_uuid}/preview/regenerate", tags=["preview"])
def regenerate_preview(
    session_uuid: str,
    db: Session = Depends(get_db)
):
    """
    Regenerate the preview file without downloading it.
    
    This endpoint regenerates the preview on the server but doesn't return the file.
    Use this when you just want to update the preview without triggering a download.
    """
    session = db.query(SessionModel).filter(SessionModel.uuid == session_uuid).first()
    
    if not session:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Session not found: {session_uuid}"
        )
    
    try:
        preview_service = PreviewService(db)
        preview_path = preview_service.generate_preview(session)
        
        # Verify the file exists
        preview_file = Path(preview_path)
        if not preview_file.exists():
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail="Preview file generation failed"
            )
        
        return {
            "success": True,
            "message": "Preview regenerated successfully",
            "preview_path": str(preview_path)
        }
        
    except Exception as e:
        logger.error(f"Error regenerating preview for session {session_uuid}: {str(e)}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to regenerate preview: {str(e)}"
        )


@router.get("/sessions/{session_uuid}/preview/edit", response_class=HTMLResponse, tags=["preview"])
def get_preview_editor(
    request: Request,
    session_uuid: str,
    db: Session = Depends(get_db)
):
    """
    Interactive preview editor page.
    
    Shows all fields with their values in an editable form.
    Allows real-time updates and preview regeneration.
    """
    session = db.query(SessionModel).filter(SessionModel.uuid == session_uuid).first()
    
    if not session:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Session not found: {session_uuid}"
        )
    
    # Get all field values
    field_values = db.query(FieldValue).filter(
        FieldValue.session_id == session.id
    ).all()
    
    fields_data = []
    for fv in field_values:
        template_field = fv.template_field
        if not template_field:
            continue
            
        fields_data.append({
            "id": fv.id,
            "field_key": template_field.field_key,
            "display_name": template_field.display_name,
            "placeholder": template_field.placeholder,
            "current_value": fv.final_value or "",
            "extracted_value": fv.extracted_value or "",
            "manual_value": fv.manual_value or "",
            "description": template_field.description or "",
            "is_manual": fv.manual_value is not None
        })
    
    # Sort by field_order if available
    fields_data.sort(key=lambda x: (x.get('field_order', 999), x['display_name']))
    
    # Generate initial preview
    try:
        preview_service = PreviewService(db)
        preview_path = preview_service.generate_preview(session)
        preview_generated = True
    except Exception as e:
        logger.error(f"Failed to generate initial preview: {str(e)}")
        preview_generated = False
        preview_path = None
    
    return templates.TemplateResponse(
        "preview_editor.html",
        {
            "request": request,
            "session_uuid": session_uuid,
            "fields": fields_data,
            "preview_url": f"/api/v1/sessions/{session_uuid}/preview",
            "preview_generated": preview_generated
        }
    )
